name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:

  # build index listing
  index:
    name: Build Index
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: actions/setup-java@v4
        with:
          java-version: 13
      - run: make install
      - run: make index
      - uses: actions/upload-artifact@v1
        with:
          name: index.xml
          path: index.xml
      - uses: actions/upload-artifact@v1
        with:
          name: index.html
          path: index.html
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[Skip CI]') }}

  # compute file digests
  digest:
    name: Digest Files
    steps:
      - uses: actions/checkout@v2
      - run: make checksums
      - run: tar --xz --create --file digests.txz *.md5 *.sha256
      - uses: actions/upload-artifact@v1
        with:
          name: digests.txz
          path: digests.txz
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[Skip CI]') }}

  # publish gh-pages
  push:
    name: Publish Pages
    needs:
      - digest
      - index
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: index.xml
          path: /home/runner/work/blob/blob
      - uses: actions/download-artifact@v1
        with:
          name: index.html
          path: /home/runner/work/blob/blob
      - uses: actions/download-artifact@v1
        with:
          name: digests.txz
          path: /tmp
      - run: |
          tar --xz --extract --file /tmp/digests.txz
          mkdir --parent /tmp/build
          rsync --delete --links --recursive --include index.\* --include status.xml --exclude-from excludes.patterns ${GITHUB_WORKSPACE:-.}/ /tmp/build
      - run: |
          git init
          git checkout --orphan gh-pages
          git config user.email "mail@ashenm.dev"
          git config user.name "Ashen Gunaratne"
          echo "blob.ashenm.dev" | tee CNAME
          git add --all .
          git commit --quiet --message "Deploy blob.ashenm.dev to github.com/ashenm/blob.git:gh-pages"
          git push --force --quiet "https://${{ secrets.ENDPOINT_TOKEN }}@github.com/ashenm/blob.git" "gh-pages:gh-pages"
          git show --stat-count=10 HEAD
        working-directory: /tmp/build
    runs-on: ubuntu-latest

  slack:
    name: Slack
    needs:
      - push
    if: ${{ always() }}
    steps:
      - uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: "#github"
          name: "GitHub Workflow"
    runs-on: ubuntu-latest

# vim: set expandtab shiftwidth=2 syntax=yaml:
